apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    environment: dev
    name: frontend
    project: expense
    component: frontend
  ports:
  - protocol: TCP
    port: 80 # service-port
    targetPort: 80  #target-port