# this works only in cloud.our cloud provider is aws. so aws type of lb will be created
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    environment: dev
    name: frontend
    project: expense
    component: frontend
  ports:
  - protocol: TCP
    port: 80 # service-port
    targetPort: 80  #target-port
    nodePort: 32761