apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "expense-ebs" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
# when storage class is created, we need not create pv. pv and volume creation are automatically done.
# we have to create pvc only. im making claim directly.
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-dynamic
  labels: 
    purpose: ebs-static
    project: expense
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1f # give your node region if nodes are created in diff regions
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic # we have to give claim name
---
